### ISSUE TITLE
Il n'est pas possible de supprimer une facture

### ISSUE THREAD

**Issue by DavidBruant** [comptanar/comptanar.github.io#25]
Si je vais sur https://comptanar.github.io/comptabilite/factures?org=fausse-echappee-belle&repo=comptabilite
je ne peux pas supprimer la facture

Version du code déployé : https://github.com/comptanar/comptanar.github.io/tree/e90515070cbbd92bec137e926d20cd51c33fb1b1

**Comment by DavidBruant** [comment]
L'erreur dans la console est `can't access property "getFullYear", t is undefined`

Je crois que c'est une mauvaise interaction entre

https://github.com/comptanar/comptanar.github.io/blob/e90515070cbbd92bec137e926d20cd51c33fb1b1/source/front-end/composants/Tableau.svelte#L153

et

https://github.com/comptanar/comptanar.github.io/blob/e90515070cbbd92bec137e926d20cd51c33fb1b1/source/front-end/composants/screens/Factures.svelte#L49-L51

et 

https://github.com/comptanar/comptanar.github.io/blob/e90515070cbbd92bec137e926d20cd51c33fb1b1/source/front-end/actions.js#L162

En gros, les fonctions actions sont toujours appelées avec un seul argument `i` et dans ce cas-là, la fonction a besoin de 2 arguments

**Comment by elegaanz** [comment]
Oui surtout que `i` est l'indice de l'item et pas l'item en lui-même. Je viens de faire un fix, je fais une mini PR :)

**Comment by DavidBruant** [comment]
Côté solution, je propose de déplacer le bouton de suppression dans le formulaire d'édition (ça réduit aussi le risque d'erreur de clic dans la foulée)

et dans la foulée, supprimer la fonctionnalité des items actions. On met toutes les actions dans le formulaire pour le moment, ça a l'air ok

**Comment by elegaanz** [comment]
Okay, je change mon fix alors

**Comment by DavidBruant** [comment]
merci

**Comment by DavidBruant** [comment]
Aucune urgence, je vais passer à autre chose

Si on avait eu les types, ça aurait pu être attrapé par le compilo TypeScript, je pense

Est-ce que ça serait ok pour toi de rajouter des types d'une manière qui aurait attrapé cette erreur (si c'est encore pertinent après la suppression des `itemActions`, j'ai du mal à voir) ?

**Comment by DavidBruant** [comment]
Merci beaucoup pour ta réactivité ^^

**Comment by DavidBruant** [comment]
oki, ça roule, merci d'avoir essayé
