### ISSUE TITLE
Chiffre avec des décimales

### ISSUE THREAD

**Issue by maiwann** [comptanar/comptanar.github.io#28]
Est-ce que dans les chiffres à virgules, il vaut mieux mettre des points, ou des virgules ? ou autre chose ?

**Comment by DavidBruant** [comment]
J'avais pas pensé à cette question

J'ai envie que la réponse soit qu'on écrit ce qu'on veut (point ou virgule) et le logiciel compense et je pense que c'est facile à faire

**Comment by DavidBruant** [comment]
Je viens de tester et les `<input type="number">` acceptent les 2 et je n'ai pas vu de différence
Quand on pre-remplit le champ, ça met une virgule. J'imagine que mon navigateur est configuré en français et sait que je préfère sûrement les virgules

Je considère cette issue résolue et si y'a un problème qui vient avec ces histoires de décimaux à virgule, on verra avec ce nouveau problème
