### ISSUE TITLE
Gérer correctement les exercices des années passées

### ISSUE THREAD

**Issue by elegaanz** [comptanar/comptanar.github.io#30]
Je sais pas exactement ce dont il y a besoin pour ça dans le code et en terme d'interface, mais actuellement rien ne marche si on met des dates hors 2023.

**Comment by DavidBruant** [comment]
Je me l'assigne, je vais le résoudre à l'intérieur de #31 et j'imagine que la solution sera suffisamment générique pour que ça marche partout (sûrement une détection+ajoutant-si-manquant dans les mutations liées à `state.opérationsHautNiveauByYear`)
