### ISSUE TITLE
Faire un composant pour sélectionner une date ?

### ISSUE THREAD

**Issue by elegaanz** [comptanar/comptanar.github.io#41]
Ou en importer un tout fait depuis NPM, mais là on a de plus en plus d'endroits où on doit sélectionner des dates (surtout avec la branche sur laquelle je suis en train de travailler) et à chaque fois on doit faire la petite danse de convertir entre un string au format `yyyy-MM-dd` et une vraie `Date`.

**Comment by DavidBruant** [comment]
Bien vu !

Je crois que le composant que nous souhaitons est ici : https://svelte.dev/repl/dc963bbead384b69aad17824149d6d27?version=3.25.1 (ou suffisamment proche)
