### ISSUE TITLE
L'initialisation de compte ne marche pas la première fois

### ISSUE THREAD

**Issue by elegaanz** [comptanar/comptanar.github.io#47]
On regarde les autres suffixes déjà utilisés pour prendre le premier pas utilisé, mais dans le cas où on a pas d'autres suffixes, bah ça marche pas comme technique.

(ici : https://github.com/comptanar/comptanar.github.io/blob/main/source/front-end/actions.js#L392)

**Comment by DavidBruant** [comment]
Je prends celle-ci

Après avoir regardé un peu, j'imagine que ça va être un travail plus large qui va toucher aux histoires de fiches de paie et de salariat/é.es

**Comment by DavidBruant** [comment]
Le seul endroit où y'a des appels à `initCompteSiBesoin`, c'est le composant FicheDePaie. Notamment pour créer un `compteAssocié·e`

Dans les histoires de fiche de paie, je réalise que ça parle beaucoup de `compteAssocié·e` alors que ça n'est pas forcément lié (c'était dans https://github.com/comptanar/comptanar.github.io/pull/45 et chuis passé à côté)

Suite à la discussion qu'on avait eu, je réalise que le type `SpécifiqueÉmissionFicheDePaie` est cassé. Il faudrait y ajouter la personne ou le salariat associé (et plu un compte vu qu'on ne fait plus les comptes salarié.e)

Je compte faire les choses suivantes : 
- [ ] Rajouter un champ avec un identifiant de personne dans la fiche de paie
- [ ] Permettre de choisir une personne dans un `<select>` parmi les salariats actifs
- [ ] J'imagine supprimer `initCompteSiBesoin` (et je pense que ça va résoudre #53 dans la foulée)

**Comment by DavidBruant** [comment]
Y'a beaucoup trop de dates
Je vais faire #41
