### ISSUE TITLE
Je n'arrive pas à voir le caractère "🠒"

### ISSUE THREAD

**Issue by DavidBruant** [comptanar/comptanar.github.io#54]
C'est dans les fiches de paie

![Capture d’écran 2023-07-08 à 11 08 17](https://github.com/comptanar/comptanar.github.io/assets/165829/919697ef-a591-4dad-b31a-0975b4e7e4a1)

Quel est ce caractère ? Est-ce qu'on peut le remplacer par une flèche "plus ancienne" ?

**Comment by elegaanz** [comment]
Je crois que j'ai pris cette flèche parce qu'elle était un peu sympa visuellement, mais n'importe quelle autre caractère plus commun fera l'affaire.

**Comment by DavidBruant** [comment]
Oki, ça roule, je le change
